### ISSUE TITLE
Make max buffer size for Fluency configurable

### ISSUE THREAD

**Issue by ogibayashi** [treasure-data/kafka-fluentd-consumer#15]
Hello,

I recently started using kafka-fluentd-consumer. 
After I started the process, I sometimes got following errors in my fluentd process log.

```
2016-06-03 12:04:04 +0900 [warn]: Size of the emitted data exceeds buffer_chunk_limit.
2016-06-03 12:04:04 +0900 [warn]: This may occur problems in the output plugins ``at this server.``
2016-06-03 12:04:04 +0900 [warn]: To avoid problems, set a smaller number to the buffer_chunk_limit
2016-06-03 12:04:04 +0900 [warn]: in the forward output ``at the log forwarding server.``
```

I guess the reason is that I configured buffer_chunk_limit to 1MB in my fluentd config, while kafka-fluentd-consumer(Fluency) sends with larger size.
Fluency provides the way to set max buffer size, so if I can configure that through fluentd-consumer.properties , it would be helpful.

**Comment by repeatedly** [comment]
It seems acceptable.
I will work on it later.

**Comment by repeatedly** [comment]
I will fix this problem by adding these parameters: https://github.com/komamitsu/fluency#advanced-buffer-configuration

**Comment by tschroeder-zendesk** [comment]
Any progress on this?

**Comment by repeatedly** [comment]
@komamitsu is now improving configuration setup for specifying buffer parameters.
I'm now waiting this change.

**Comment by komamitsu** [comment]
I released fluency 1.0.0 that has new APIs `Fluency.Config#setBufferChunkInitialSize` and `Fluency.Config#setBufferChunkRetentionSize`. You can use them like this

```
    fluency = Fluency.defaultFluency(
            new Fluency.Config()
                    .setBufferChunkInitialSize(64 * 1024)
                    .setBufferChunkRetentionSize(512 * 1024));
```

**Comment by tschroeder-zendesk** [comment]
@repeatedly Any ETA on this? It happens to a bit of a blocker for me.

**Comment by repeatedly** [comment]
I'm now working on it.

**Comment by repeatedly** [comment]
Released v0.3.0

**Comment by tschroeder-zendesk** [comment]
Awesome. Thanks!

**Comment by ogibayashi** [comment]
Thank you for the fix. I have upgraded to 0.3.0 and it is working fine.
